name: Build
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - develop
      - release/*
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-2022 ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@master
      with:
        node-version: 16

    - name: install dependencies
      run: yarn
      shell: bash

    - name: build
      run: yarn make
      shell: bash
