name: Build
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
      - release/*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: yarn
    - name: build
      run: yarn make
